# Generated by Django 3.2.8 on 2021-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('cod_cert', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
                ('datacompra', models.DateField()),
                ('datavencimento', models.DateField()),
                ('tipo', models.CharField(blank=True, choices=[('A1', 'A1'), ('A3', 'A3')], max_length=2)),
                ('fone', models.CharField(blank=True, max_length=15)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('funcionario', models.CharField(blank=True, max_length=40)),
                ('datacadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificados',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=40)),
                ('permissao', models.CharField(default='administrador', max_length=15)),
                ('datacadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
