# Generated by Django 3.2.8 on 2021-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='permissao',
            field=models.CharField(max_length=15),
        ),
    ]
