# Generated by Django 3.2.8 on 2021-10-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='permissao',
        ),
    ]
